project_name: nestor
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - id: nestor-build
    env:
      - CGO_ENABLED=0
    main: ./cmd/nestor/main.go
    goos:
      - darwin
    goarch:
      - amd64

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
