nestor: "1.0"
application:
  name: myapp
# list optional resources that we need i the application
resources:
  - id: nestor.res.logGroup.mainEventBridgeTarget

lambdas:
  - id: 100-snoop
    permissions:
      - resourceId: nestor.res.dynamoDbTable.main
        actions:
          - operation: read
          - operation: write
  - id: 200-s3-uploads
    permissions:
      - resourceId: nestor.res.s3.upload
        actions:
          - operation: read
          - operation: delete

triggers:
  - type: s3
    lambda: s3-uploads
    # s3:
    #   prefix: /upload
    #   suffix: *.png
