nestor: "1.0"
application:
  name: myapp
# list optional resources that we need in the application
resources:
  - id: nestor.res.logGroup.mainEventBridgeTarget

lambdas:
  - id: 100-snoop
    permissions:
      - resourceId: nestor.res.dynamoDbTable.main
        actions:
          - operation: read
          - operation: write
  - id: 200-s3-uploads
    permissions:
      - resourceId: nestor.res.s3.upload
        actions:
          - operation: read
          - operation: delete

triggers:
  - s3upload:
    - lambda: 200-s3-uploads
      prefix: /upload
      suffix: "*.png"
