nestor: "1.0"
application:
  name: myapp
# list optional resources that we need in the application
resources:
  cognito_userpool:
    - id: main
  dynamodb_table:
    - id: main
  eventbridge_bus:
    - id: main
  cloudwatchlogs_group:
    - id: main
  s3_bucket:
    - id: upload
    - id: store
  apigateway_http:
    - id: main
  lambda_function:
    - id: 100-snoop
      permissions:
        - resourceId: resources.dynamodb_table.main
          actions:
            - operation: read
            - operation: write
    - id: 200-s3-uploads
      permissions:
        - resourceId: resources.s3_bucket.upload
          actions:
            - operation: read
            - operation: delete

triggers:
  s3copy:
    - bucketId: resources.s3_bucket.upload
      lambdaId: resources.lambda_function.200-s3-uploads
      prefix: /upload
      suffix: "*.png"
